"""PDF Export Service — generates professional PDF documents of chat conversations.

Uses ReportLab to generate PDFs entirely on the backend.
Returns application/pdf bytes for the API endpoint to stream.

Features:
  - CrimeAI branded header with title and metadata
  - Officer name, role, and export date
  - All chat messages with role labels (Officer / CrimeAI)
  - Markdown rendering (bold, headings, lists)
  - Conversation summary (total messages)
  - Footer with "Generated by CrimeAI | Confidential"
"""

import re
from datetime import datetime, timezone
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.logging import get_logger

logger = get_logger(__name__)

NAVY = colors.HexColor("#1B2A4A")
ACCENT_BLUE = colors.HexColor("#2B59C3")
LIGHT_GRAY = colors.HexColor("#F4F6F8")
MEDIUM_GRAY = colors.HexColor("#E0E4E8")
DARK_GRAY = colors.HexColor("#4A5568")
TEXT_DARK = colors.HexColor("#1A202C")
SUCCESS_GREEN = colors.HexColor("#38A169")

_styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle("PDF_Title", parent=_styles["Title"],
    fontName="Helvetica-Bold", fontSize=22, leading=28,
    textColor=NAVY, alignment=TA_CENTER, spaceAfter=2 * mm)

SUBTITLE_STYLE = ParagraphStyle("PDF_Subtitle", parent=_styles["Normal"],
    fontName="Helvetica", fontSize=10, leading=14,
    textColor=DARK_GRAY, alignment=TA_CENTER, spaceAfter=6 * mm)

SECTION_HEADER = ParagraphStyle("PDF_SectionHeader", parent=_styles["Heading2"],
    fontName="Helvetica-Bold", fontSize=13, leading=18,
    textColor=NAVY, spaceBefore=4 * mm, spaceAfter=2 * mm)

INFO_VALUE = ParagraphStyle("PDF_InfoValue", parent=_styles["Normal"],
    fontName="Helvetica", fontSize=10, leading=14, textColor=TEXT_DARK)

MSG_LABEL_USER = ParagraphStyle("PDF_MsgUser", parent=_styles["Normal"],
    fontName="Helvetica-Bold", fontSize=10, leading=14,
    textColor=ACCENT_BLUE, spaceBefore=3 * mm, spaceAfter=0)

MSG_LABEL_AI = ParagraphStyle("PDF_MsgAI", parent=_styles["Normal"],
    fontName="Helvetica-Bold", fontSize=10, leading=14,
    textColor=SUCCESS_GREEN, spaceBefore=3 * mm, spaceAfter=0)

MSG_BODY = ParagraphStyle("PDF_MsgBody", parent=_styles["Normal"],
    fontName="Helvetica", fontSize=9.5, leading=14,
    textColor=TEXT_DARK, spaceBefore=1 * mm, spaceAfter=0, leftIndent=4 * mm)

TIMESTAMP_STYLE = ParagraphStyle("PDF_Ts", parent=_styles["Normal"],
    fontName="Helvetica-Oblique", fontSize=7.5, leading=10,
    textColor=MEDIUM_GRAY, spaceAfter=2 * mm, leftIndent=4 * mm)

SUM_VAL = ParagraphStyle("PDF_SumVal", parent=_styles["Normal"],
    fontName="Helvetica-Bold", fontSize=20, leading=26,
    textColor=ACCENT_BLUE, alignment=TA_CENTER)

SUM_LBL = ParagraphStyle("PDF_SumLbl", parent=_styles["Normal"],
    fontName="Helvetica", fontSize=8, leading=11,
    textColor=DARK_GRAY, alignment=TA_CENTER)


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    margin = 2 * cm
    canvas.setStrokeColor(ACCENT_BLUE)
    canvas.setLineWidth(0.5)
    canvas.line(margin, h - 1.5 * cm, w - margin, h - 1.5 * cm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(DARK_GRAY)
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    canvas.drawCentredString(w / 2, 1 * cm, f"Generated by CrimeAI  |  Confidential  |  {now_str}")
    canvas.restoreState()


def _md_to_paragraphs(text, style):
    paragraphs = []
    lines = text.split("\n")
    buffer = []
    for line in lines:
        s = line.strip()
        if not s:
            if buffer:
                paragraphs.append(Paragraph("\n".join(buffer), style))
                buffer = []
            continue
        if s.startswith("### "):
            if buffer:
                paragraphs.append(Paragraph("\n".join(buffer), style))
                buffer = []
            h = ParagraphStyle("h3", parent=SECTION_HEADER, fontSize=11, leading=15)
            paragraphs.append(Paragraph(s[4:], h))
            continue
        if s.startswith("## "):
            if buffer:
                paragraphs.append(Paragraph("\n".join(buffer), style))
                buffer = []
            h = ParagraphStyle("h2", parent=SECTION_HEADER, fontSize=12, leading=16)
            paragraphs.append(Paragraph(s[3:], h))
            continue
        if s.startswith("# "):
            if buffer:
                paragraphs.append(Paragraph("\n".join(buffer), style))
                buffer = []
            h = ParagraphStyle("h1", parent=SECTION_HEADER, fontSize=14, leading=18)
            paragraphs.append(Paragraph(s[2:], h))
            continue
        if s.startswith("- ") or s.startswith("* "):
            if buffer:
                paragraphs.append(Paragraph("\n".join(buffer), style))
                buffer = []
            item = s[2:]
            item = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", item)
            item = re.sub(r"\*(.+?)\*", r"<i>\1</i>", item)
            ls = ParagraphStyle("li", parent=style, leftIndent=8 * mm, bulletIndent=2 * mm)
            paragraphs.append(Paragraph("<bullet>&bull;</bullet>" + item, ls))
            continue
        p = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
        p = re.sub(r"\*(.+?)\*", r"<i>\1</i>", p)
        buffer.append(p)
    if buffer:
        paragraphs.append(Paragraph("\n".join(buffer), style))
    return paragraphs or [Paragraph(text, style)]


def generate_conversation_pdf(conversation_id, title, messages,
                               officer_name="Officer", officer_role="Officer",
                               created_at=None, updated_at=None):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
        topMargin=2.2 * cm, bottomMargin=2.2 * cm,
        leftMargin=2 * cm, rightMargin=2 * cm,
        title=f"CrimeAI Conversation #{conversation_id}",
        author="Crime Intelligence Platform")

    story = []

    story.append(Paragraph("Crime Intelligence Platform", TITLE_STYLE))
    story.append(Paragraph(
        "AI-Powered Investigation Assistant &mdash; Conversation Report",
        SUBTITLE_STYLE))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT_BLUE,
                             spaceBefore=0, spaceAfter=4 * mm))

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    created_str = created_at.strftime("%Y-%m-%d %H:%M UTC") if created_at else "N/A"

    info_data = [
        [Paragraph("Officer Information", SECTION_HEADER), "", ""],
        [Paragraph(f"<b>Name:</b> {officer_name}", INFO_VALUE),
         Paragraph(f"<b>Role:</b> {officer_role}", INFO_VALUE),
         Paragraph(f"<b>Export:</b> {now_str}", INFO_VALUE)],
        [Paragraph(f"<b>Conversation:</b> #{conversation_id}", INFO_VALUE),
         Paragraph(f"<b>Messages:</b> {len(messages)}", INFO_VALUE),
         Paragraph(f"<b>Created:</b> {created_str}", INFO_VALUE)],
    ]
    info_table = Table(info_data, colWidths=[doc.width / 3] * 3)
    info_table.setStyle(TableStyle([
        ("SPAN", (0, 0), (-1, 0)),
        ("BACKGROUND", (0, 1), (-1, -1), LIGHT_GRAY),
        ("BOX", (0, 1), (-1, -1), 0.5, MEDIUM_GRAY),
        ("INNERGRID", (0, 1), (-1, -1), 0.25, MEDIUM_GRAY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ("LEFTPADDING", (0, 1), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 4 * mm))

    if title and title != "New Chat":
        story.append(Paragraph(f"<b>Conversation:</b> {title}", INFO_VALUE))
        story.append(Spacer(1, 3 * mm))

    story.append(HRFlowable(width="100%", thickness=0.5, color=MEDIUM_GRAY,
                             spaceBefore=2 * mm, spaceAfter=4 * mm))
    story.append(Paragraph("Conversation", SECTION_HEADER))
    story.append(Spacer(1, 2 * mm))

    for i, msg in enumerate(messages):
        role = msg.get("role", "user")
        text = msg.get("message", "")
        ts = msg.get("created_at")
        ts_str = ""
        if ts:
            ts_str = (ts.strftime("%Y-%m-%d %H:%M")
                      if hasattr(ts, "strftime") else str(ts)[:16])

        if role == "user":
            story.append(Paragraph("Officer &mdash; Question", MSG_LABEL_USER))
        else:
            story.append(Paragraph("CrimeAI &mdash; Response", MSG_LABEL_AI))
        if ts_str:
            story.append(Paragraph(ts_str, TIMESTAMP_STYLE))
        story.extend(_md_to_paragraphs(text, MSG_BODY))
        if i < len(messages) - 1:
            story.append(Spacer(1, 2 * mm))

    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT_BLUE,
                             spaceBefore=2 * mm, spaceAfter=4 * mm))
    story.append(Paragraph("Conversation Summary", SECTION_HEADER))

    user_count = sum(1 for m in messages if m.get("role") == "user")
    ai_count = sum(1 for m in messages if m.get("role") == "assistant")

    summary_data = [
        [Paragraph(str(len(messages)), SUM_VAL),
         Paragraph(str(user_count), SUM_VAL),
         Paragraph(str(ai_count), SUM_VAL)],
        [Paragraph("Total Messages", SUM_LBL),
         Paragraph("Officer Questions", SUM_LBL),
         Paragraph("CrimeAI Responses", SUM_LBL)],
    ]
    summary_table = Table(summary_data, colWidths=[doc.width / 3] * 3)
    summary_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ("TOPPADDING", (0, 1), (-1, 1), 2),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 6),
    ]))
    story.append(summary_table)

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    logger.info("PDF generated for conversation %d: %d messages, %d pages",
                conversation_id, len(messages), doc.page)
    return buf
